version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: cosk
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: Jawda
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: